[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "musicleague"
dependencies = [
  "duckdb>=1.5.0",
  "openpyxl>=3.0.0",
  "pandas>=3.0.0",
  "spotipy>=2.25.0",
]
authors = [
  { name="Michael Manos", email="Michael.A.Manos@gmail.com" },
]
description = "Package to read Music League export data into a local database"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dynamic = ["version"]

[project.urls]
Homepage = "https://github.com/MichaelManos/musicleague"
Issues = "https://github.com/MichaelManos/musicleague/issues"

[tool.hatch.build]
include = [
  "musicleague/*.py",
  "ddl/*.sql",
]

[tool.hatch.version]
path = "musicleague/_version.py"
